### ISSUE TITLE
Duplicate initiative associations

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/castokr#2]
Not sure if it's expected behaviour, but when logging a new interaction that's associated to an initiative (for a contact that's already associated with the initiative being 'logged' against) it returns two instances of initiative participation, e.g.

![Screenshot 2019-04-26 at 10 49 52](https://user-images.githubusercontent.com/7393302/56799559-18201800-6811-11e9-9c68-a853e7f7b749.png)

Moreover, when viewing the initiative duplicate records of the contact appear in the 'Participating contacts' list.

FYI, here is the timeline for the scenario...

![Screenshot 2019-04-26 at 10](https://user-images.githubusercontent.com/7393302/56799446-e0b16b80-6810-11e9-8737-11122e0fa110.png)

**Comment by andrewflett** [comment]
Fixed in next release
